name: Build and Push Docker image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read   # packages: write pas nécessaire ici car on n'utilise pas GITHUB_TOKEN

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR with PAT
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: thecabs
          password: ${{ secrets.GHCR_PAT }}

      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

